# Generated by Django 5.0.4 on 2024-05-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_configuser_user_alter_configuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custompermission",
            old_name="permission",
            new_name="value",
        ),
    ]
