# Generated by Django 5.0.4 on 2024-05-16 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_rename_permission_custompermission_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuser",
            name="role",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config",
                to="system.role",
            ),
        ),
    ]
