# Generated by Django 5.0.4 on 2024-05-08 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("length_dimension", models.IntegerField()),
                ("height_dimension", models.IntegerField()),
                ("country_of_origin", models.CharField(max_length=50)),
                ("expiry_date", models.DateField(default=datetime.date.today)),
                ("customs_tariff_number", models.CharField(max_length=20)),
                ("packagin_information", models.TextField(blank=True, null=True)),
                ("insurance_value", models.IntegerField(null=True)),
            ],
        ),
    ]
