# Generated by Django 5.0.4 on 2024-05-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="commodity",
            name="storage_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logistic.storagecondition",
            ),
        ),
    ]
