# Generated by Django 5.0.4 on 2024-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0002_storagecondition_commodity_storage_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagecondition",
            name="title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
