# Generated by Django 5.0.4 on 2024-05-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0003_storagecondition_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="storage_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commodities",
                to="logistic.storagecondition",
            ),
        ),
    ]
