# Generated by Django 5.0.4 on 2024-05-15 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0004_alter_commodity_storage_condition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodHazardClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_location", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "contact_information",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("storage_capacity", models.IntegerField()),
                ("horse_power", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("load_capacity", models.IntegerField()),
                (
                    "insurance_information",
                    models.TextField(blank=True, max_length=50, null=True),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
