# Generated by Django 5.0.4 on 2024-05-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0005_goodhazardclass_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="good_hazard_class",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="good_hazard_class",
                to="logistic.goodhazardclass",
            ),
            preserve_default=False,
        ),
    ]
