# Generated by Django 5.0.4 on 2024-05-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0006_commodity_good_hazard_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="good_hazard_class",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="good_hazard_class",
                to="logistic.goodhazardclass",
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="storage_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commodities",
                to="logistic.storagecondition",
            ),
        ),
    ]
