# Generated by Django 5.0.4 on 2024-05-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistic",
            "0009_rename_packagin_information_commodity_packaging_information_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="logistic.warehouse",
            ),
        ),
    ]
